name = "SimpleAutoDiff"
uuid = "3475a125-4bee-46e3-a7a2-285784190cbf"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de> and contributors"]
version = "0.1.0-DEV"

[deps]
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
DiffRules = "1.10"
LogExpFunctions = "0.3.2"
NaNMath = "1"
SpecialFunctions = "2"
julia = "1.10"
